=== fabiocav/schemastore/src/schemas/json/azurefunctions-host.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "JSON schema for Azure Functions host.json files.",
  "properties": {
    "id": {
        "type": "string",
        "description": "The unique ID for this job host."
    },
    "functions": {
      "type": "array",
        "items": {
            "type": "string",
            "uniqueItems": true
        },
      "description": "The list of functions the host should load."
    },
    "watchDirectories": {
      "type": "array",
        "items": {            
            "type": "string",
            "uniqueItems": true
        },
      "description": "A list of directories that should be monitored for file changes. Function directories are watched by default."
    },
    "functionTimeout": {
      "type": "string",
      "pattern": "^\\d\\d:\\d\\d:\\d\\d$",
      "description": "Value indicating the timeout duration for all functions. In Dynamic SKUs, the valid range is from 1 second to 5 minutes and the default value is 5 minutes. In Paid SKUs there is no limit and the default value is null (indicating no timeout)."
    },
    "http": {
      "type": "object",
      "description": "Configuration settings for 'http' triggers.",
      "properties": {
        "routePrefix": {
          "type": "string",
          "default": "api",
          "description": "Defines the default route prefix that applies to all routes. Default is 'api'. Use an empty string to remove the prefix."
        }
      },
      "required": [
        "routePrefix"
      ]
    },
    "queues": {
      "type": "object",
      "description": "Configuration settings for 'queue' triggers.",
      "properties": {
        "maxPollingInterval": {
          "type": "integer",
          "description": "The maximum interval in milliseconds between queue polls. The default is 1 minute."
        },
        "batchSize": {
          "type": "integer",
          "default": 16,
          "maximum": 32,
          "minimum": 1,
          "description": "The number of queue messages to retrieve and process in parallel (per job function)."
        },
        "maxDequeueCount": {
          "type": "integer",
          "default": 5,
          "description": "The number of times to try processing a message before moving it to the poison queue."
        },
        "newBatchThreshold": {
          "type": "integer",
          "description": "The threshold at which a new batch of messages will be fetched. The default is batchSize/2."
        }
      }
    },
    "serviceBus": {
      "type": "object",
      "description": "Configuration settings for 'serviceBus' triggers.",
      "properties": {
        "maxConcurrentCalls": {
          "type": "integer",
          "default": 16,
          "description": "The maximum number of concurrent calls to the callback the message pump should initiate."
        },
        "prefetchCount": {
          "type": "integer",
          "description": "The default PrefetchCount that will be used by the underlying MessageReceiver."
        }
      }
    },
    "eventHub": {
      "type": "object",
      "description": "Configuration settings for 'eventHub' triggers.",
      "properties": {
        "maxBatchSize": {
          "type": "integer",
          "default": 1000,
          "description": "The maximum event count received per receive loop."
        },
        "prefetchCount": {
          "type": "integer",
          "default": 100,
          "description": "The default PrefetchCount that will be used by the underlying EventProcessorHost."
        }
      }
    },
    "tracing": {
      "type": "object",
      "description": "The tracing level used for console logging.",
      "properties": {
        "consoleLevel": {
          "type": "string",
          "enum": [ "off", "error", "warning", "info", "verbose" ],
          "default": "info",
          "description": "An explanation about the purpose of this instance."
        },
        "fileLoggingMode": {
          "type": "string",
          "description": "Value determining what level of file logging is enabled.",
          "enum": [ "never", "always", "debugOnly" ]
        }
      }
    },
    "singleton": {
      "type": "object",
      "description": "Configuration settings for Singleton lock behavior.",
      "properties": {
        "lockPeriod": {
          "type": "string",
          "pattern": "^\\d\\d:\\d\\d:\\d\\d$",
          "default": "00:00:15",
          "description": "The period that function level locks are taken for (they will auto renew)."
        },
        "listenerLockPeriod": {
          "type": "string",
          "pattern": "^\\d\\d:\\d\\d:\\d\\d$",
          "default": "00:01:00",
          "description": "The period that listener locks are taken for."
        },
        "listenerLockRecoveryPollingInterval": {
          "type": "string",
          "pattern": "^\\d\\d:\\d\\d:\\d\\d$",
          "default": "00:01:00",
          "description": "The time interval used for listener lock recovery if a listener lock couldn't be acquired on startup."
        },
        "lockAcquisitionTimeout": {
          "type": "string",
          "pattern": "^\\d\\d:\\d\\d:\\d\\d$",
          "default": "00:01:00",
          "description": "The maximum amount of time the runtime will try to acquire a lock."
        },
        "lockAcquisitionPollingInterval": {
          "type": "string",
          "pattern": "^\\d\\d:\\d\\d:\\d\\d$",
          "description": "The interval between lock acquisition attempts."
        }
      }
    }
  }
}

=== fabiocav/schemastore/src/test/azurefunctions-host/azurefunctions-host.json
{
    "id": "testid",
    "tracing": {
        "consoleLevel": "info",
        "fileLoggingMode": "never"
    },
    "watchDirectories": [
        "test",
        "test1"
    ],
    "functionTimeout": "00:05:00",
    "singleton": {
        "listenerLockPeriod": "00:01:00",
        "listenerLockRecoveryPollingInterval": "00:01:00",
        "lockAcquisitionPollingInterval": "00:00:30",
        "lockAcquisitionTimeout": "00:00:30",
        "lockPeriod": "00:00:15"
    },
    "eventHub": {
        "maxBatchSize": 1000,
        "prefetchCount": 100
    },
    "functions": [
        "testfunction1",
        "testfunction2"
    ],
    "http": {
        "routePrefix": "api"
    },
    "queues": {
        "batchSize": 16,
        "maxDequeueCount": 5,
        "maxPollingInterval": 60000,
        "newBatchThreshold": 10
    },
    "serviceBus": {
        "maxConcurrentCalls": 16,
        "prefetchCount": 100
    }
}
